### ISSUE TITLE
Replace deprecated 'request-promise' library with 'axios' for network calls

### ISSUE THREAD

**Issue by omeryousaf** [omeryousaf/sasta-miner#22]
## Description
Currently we are using https://github.com/request/request-promise to make api calls to CMC (CoinMarketCap) web service but this library is deprecated (no longer supported), 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/6904200/118391851-cd6bd580-b64f-11eb-8425-b53d9e77107e.png">

so we need to replace it with an actively supported library like https://github.com/axios/axios

## Acceptance Criteria
Use 'axios' instead of 'request-promise' for all network calls in code.

**Comment by Shapokhan** [comment]
Sure, will start working on this soon inshallah.
