### ISSUE TITLE
Coins list fetching api call via 'coingecko-api' library fails with parse errors a lot

### ISSUE THREAD

**Issue by omeryousaf** [omeryousaf/sasta-miner#24]
## Description
The coins list api call we make at the CoinGecko api service, returns with 
```
SyntaxError: Unexpected token e in JSON at position 0
at JSON.parse (<anonymous>)
at IncomingMessage.<anonymous> (...miner/node_modules/coingecko-api/lib/CoinGecko.js:864:25)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (internal/streams/readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
error.
I have logged an issue with the library's github issues: https://github.com/miscavage/CoinGecko-API/issues/17.

## Acceptance Criteria
This api call should work without errors.

**Comment by Shapokhan** [comment]
Fixed by PR #37

**Comment by zakjanzi** [comment]
Hey @Shapokhan , how exactly does the mentioned PR fix it? I am still running into this issue.

**Comment by omeryousaf** [comment]
i think we ended up switching to calling the [coingecko platform API](https://www.coingecko.com/en/api/documentation) directly 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/6904200/234471750-93ba30f4-37ba-4aa2-94ec-6a13d9d7e400.png">
via https://github.com/omeryousaf/sasta-miner/pull/30
