### ISSUE TITLE
CG down since 2 days

### ISSUE THREAD

**Issue by code4crypto** [omeryousaf/sasta-miner#55]
CG listings not working since 2 days, need to figure out frequency of our calls where we don't get blocked like this

**Comment by omeryousaf** [comment]
Seems to be down for longer than 2 days 
![image](https://user-images.githubusercontent.com/6904200/135591292-cd227f88-1302-46bc-8b9b-00a0d27fbdff.png)
https://media.giphy.com/media/a5viI92PAF89q/giphy.gif

**Comment by omeryousaf** [comment]
https://media.giphy.com/media/a5viI92PAF89q/giphy.gif

**Comment by code4crypto** [comment]
ಥ_ಥ

**Comment by omeryousaf** [comment]
Closing this in favor of the already logged #50 issue about the same complaint.
